@manualTests 
Feature: Taps Processing


  Scenario: Create a Tap (uid:85d89aac-5849-4e3d-9f4b-2cf478f91534)
    Given A Terminal is connected with the Network
    When A valid card is tapped on Terminal
    Then Terminal should display green lights and the card should be approved

  Scenario: Taps generated by Visa card are sent to Back Office (uid:79dc3dfd-658c-412d-96f8-7fa3cd387c97)
    Given A visa card is available to generate the tap "Visa"
    And a Terminal is configured
    And Back Office is configured to receive the taps from Terminal
    When Visa card is tapped on the Terminal
    Then a Tap is generated and progress of tap is monitored on WhisperMon
    And Tap is received at the Back Office with same last 4 digits of the Visa card

  Scenario Outline: Taps generated by Mastercard are sent to Back Office (<hiptest-uid>)
    Given A Mastercard is available to generate the tap
    And a Terminal is configured
    And Back Office is configured to receive the taps from Terminal
    When "<CardScheme>" is tapped on the Terminal "123"
    Then a Tap is generated and progress of tap is monitored on WhisperMon
    And Tap is received at the Back Office with same last 4 digits of the "CardScheme"

    Examples:
      | CardScheme | hiptest-uid |
      | MasterCard | uid:5429407b-72d7-4a7b-a80b-005e0fd4e426 |
      | Maestro | uid:00254aab-60c7-42df-9128-3e8509d10c58 |

  Scenario: Visa PreAuthorization Approved (uid:121f684f-7070-44f7-8e9c-121d755c49b1)
    Given A Visa card is available to generate the tap
    And a Terminal is configured
    When Visa card is tapped on the Terminal
    Then a tap is generated
    And Card Serial Number is captured from WhisperMon logs
    And a PreAuth request is created in cut_emv_offline_payment table and sent to PEM
      """
      select txn_ssn_a, txn_ssn_b, streaming_session_id, settlement_date, device_id, udsn,  authorisation_amount, request_reference_number, authorisation_response_code, authorisation_code,ud_type,ud_subtype,request_status, ud_status,settlement_amount,original_file_name,tap_id,authorisation_type from  pulse_2_vault.cut_emv_offline_payment where card_serial_number =88 and business_date = '2018-08-29' and txn_ssn_a > 5083 ALLOW FILTERING;
      """
    And PEM receives PreAuth Approved response from Acquirer

  Scenario Outline: Mastercard PreAuthorization Approved (<hiptest-uid>)
    Given A "<CardScheme>" is available to generate the tap
    And a Terminal is configured
    When "<CardScheme>" is tapped on the Terminal for the first time in the day
    Then a tap is generated
    And Card Serial Number is captured from WhisperMon logs
    And a PreAuth request is created in cut_emv_offline_payment table and sent to PEM
      """
      select txn_ssn_a, txn_ssn_b, streaming_session_id, settlement_date, device_id, udsn,  authorisation_amount, request_reference_number, authorisation_response_code, authorisation_code,ud_type,ud_subtype,request_status, ud_status,settlement_amount,original_file_name,tap_id,authorisation_type from  pulse_2_vault.cut_emv_offline_payment where card_serial_number =88 and business_date = '2018-08-29' and txn_ssn_a > 5083 ALLOW FILTERING;
      """
    And PEM receives PreAuth Approved response from Acquirer

    Examples:
      | CardScheme | hiptest-uid |
      | MasterCard | uid:8fc8ae5e-1008-478d-a623-6ca17d6d91e1 |
      | Maestro | uid:811044e5-5012-482c-aeff-c90ceacf75bd |

  Scenario: Mastercard second tap after an approved tap (uid:3bf10859-e546-4b0f-8ba5-7c055f9a4b3b)
    Given First tap of the Mastercard has been approved
    And a Terminal is configured
    When Mastercard is tapped on the Terminal second time
    Then a tap is generated
    And Card Serial Number is captured from WhisperMon logs
    And a PreAuth request is not created in cut_emv_offline_payment table
      """
      select txn_ssn_a, txn_ssn_b, streaming_session_id, settlement_date, device_id, udsn,  authorisation_amount, request_reference_number, authorisation_response_code, authorisation_code,ud_type,ud_subtype,request_status, ud_status,settlement_amount,original_file_name,tap_id,authorisation_type from  pulse_2_vault.cut_emv_offline_payment where card_serial_number =88 and business_date = '2018-08-29' and txn_ssn_a > 5083 ALLOW FILTERING;
      """

  Scenario: Visa PreAuthorization Declined and added to Deny List (uid:a9929e7b-a5c4-4046-9a42-670b6bca7a74)
    Given A Visa card is available to generate the tap
    And a Terminal is configured
    And Whisper CS is configured to add declined card to denied list
    When Visa card is tapped on the Terminal
    Then a tap is generated
    And Card Serial Number is captured from WhisperMon logs
    And a PreAuth request is created in cut_emv_offline_payment table and sent to PEM
      """
      select txn_ssn_a, txn_ssn_b, streaming_sessifsdfson_id, settlement_date, device_id, udsn,  authorisation_amount, request_reference_number, authorisation_response_code, authorisation_code,ud_type,ud_subtype,request_status, ud_status,settlement_amount,original_file_name,tap_id,authorisation_type from  pulse_2_vault.cut_emv_offline_payment where card_serial_number =88 and business_date = '2018-08-29' and txn_ssn_a > 5083 ALLOW FILTERING;
      """
    And PEM receives PreAuth Declined response from Acquirer
    And Visa card is added to the denied list

  Scenario: Visa PreAuthorization Declined and not added to Deny List (uid:59d1fbe2-2322-47ba-af94-d20de527da2f)
    Given A Visa card is available to generate the tap
    And a Terminal is configured
    And Whisper CS is configured to does not add declined card to denied list
    When Visa card is tapped on the Terminal
    Then a tap is generated
    And Card Serial Number is captured from WhisperMon logs
    And a PreAuth request is created in cut_emv_offline_payment table and sent to PEM
    And PEM receives PreAuth Declined response from Acquirer
    And Visa card is not added to the denied list
